BookStore/BookStore/Controllers/BooksController.cs
using BookStore.Models;
using BookStore.Repository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class BooksController : Controller
    {
        private readonly BookRepository _bookRepository = null;
        private readonly LanguageRepository _languageRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment = null;

        public BooksController(BookRepository bookRepository, 
           LanguageRepository languageRepository, IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _languageRepository = languageRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<ViewResult> AddNewBook(bool isSuccess=false, int bookId=0)
        {
            var model = new BookModel();
            ViewBag.Language =new SelectList(await _languageRepository.GetLanguages(),"Id","Text");
            ViewBag.IsSuccess = isSuccess;
            ViewBag.Id = bookId;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddNewBook(BookModel bookModel)
        {
            if (ModelState.IsValid)
            {
                if (bookModel.CoverImage != null)
                {
                    string folder = "booksImage/cover/";
                    bookModel.CoverImageUrl = await UploadImages(folder,bookModel.CoverImage);
                }
                if (bookModel.GalleryFiles != null)
                {
                    string folder = "booksImage/gallery/";
                    bookModel.Gallery = new List<GalleryModel>();
                    foreach (var file in bookModel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.FileName,
                            URL = await UploadImages(folder, file)
                        };
                        bookModel.Gallery.Add(gallery);
                    }
                    //bookModel.CoverImageUrl = await UploadImages(folder, bookModel.CoverImage);
                }

                if (bookModel.BookPdf != null)
                {
                    string folder = "booksImage/PDF/";
                    bookModel.BookPdfURL = await UploadImages(folder, bookModel.BookPdf);
                }

                int id = await _bookRepository.AddNewBook(bookModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(AddNewBook), new { isSuccess = true, bookId = id });
                }
            }
            ViewBag.Language = new SelectList(await _languageRepository.GetLanguages(), "Id", "Text");
            return View();
        }

        private async Task<string> UploadImages(string folderPath,IFormFile file)
        {

            folderPath += Guid.NewGuid() + "-" + file.FileName;
            
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/"+folderPath;
        }

        public async Task<ViewResult> GetAllBooks() {
            var books =await _bookRepository.GetAllBooks();
            return View(books);
        }

        [RouteAttribute("Book-Details/{id}",Name ="BookDetails")]
        public async Task<ViewResult> GetBook(int id)
        {
            var book=await _bookRepository.GetBook(id);
            return View(book);
        }

        public List<BookModel> SearchBooks(string bookName, string author)
        {
            return _bookRepository.SearchBooks(bookName,author);
        }
    }
}

BookStore/BookStore/Views/Books/AddNewBook.cshtml
@model BookModel;

@{
    ViewData["Title"] = "AddNewBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h3 class="display-4">Add New Book</h3>
    <hr />
    @if (ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Books</strong> Book added successfully
            <a asp-controller="Books" asp-action="GetBook" asp-route-id="@ViewBag.Id"
               class="btn btn-sm btn-outline-secondary">Click Check Your Book</a>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

<form enctype="multipart/form-data" asp-action="AddNewBook" asp-controller="Books" method="post">
    <div class="form-group">
        <label asp-for="LanguageId" class="control-label"></label>
        <select asp-for="LanguageId" class="form-control" asp-items="ViewBag.Language">
            <option>Please chose your language</option>
        </select>
        <span asp-validation-for="LanguageId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CoverImage" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="CoverImage" class="custom-file-input" id="customFile" />
            <label asp-for="CoverImage" class="custom-file-label">Chose File</label>
        </div>
        <span asp-validation-for="CoverImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BookPdf" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="BookPdf" class="custom-file-input" id="customFile" />
            <label asp-for="BookPdf" class="custom-file-label">Chose File</label>
        </div>
        <span asp-validation-for="BookPdf" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="GalleryFiles" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="GalleryFiles" class="custom-file-input" id="customFile" />
            <label asp-for="GalleryFiles" class="custom-file-label">Chose File</label>
        </div>
        <span asp-validation-for="GalleryFiles" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Catagory"></label>
        <input asp-for="Catagory" class="form-control" />
        <span asp-validation-for="Catagory" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" class="form-control" />
        &nbsp;<span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TotalPages"></label>
        <input asp-for="TotalPages" class="form-control" />
        <span asp-validation-for="TotalPages" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Add book" class="btn btn-primary btn" />
    </div>
</form>
</div>

BookStore/BookStore/Views/Books/GetAllBooks.cshtml
@*@model IEnumerable<BookModel>*@

<div class="container">
    <h3 class="display-4">All Books</h3>
    <hr/>
    <div class="row">
        @foreach (var item in Model)
        {
            <partial name="_bookThumbnail" model="@item" /> @*@item data pass to partial view model*@
        }
    </div>
</div>

BookStore/BookStore/Views/Books/GetBook.cshtml
@model BookModel

<div class="container">
    <div class="display-4">Book Details</div>
    <div class="row">
        <div class="col-6">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i==0 ? "active":"")"></li>
                    }
                </ol>
                <div class="carousel-inner">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <div class="@(i==0? "carousel-item active":"carousel-item")">
                            <img class="d-block w-100 h-50" src="@(string.IsNullOrEmpty(Model.CoverImageUrl) ? "/booksImage/cover/dummyImage.jpg" : Model.CoverImageUrl)" alt="@Model.Gallery[i].Name" />
                        </div>
                    }
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-6">
            <div class="row">
                <div class="col-md-12">
                    @Model.Title
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-primary">
                    <span class="form-label label-primary">By:</span>
                    <span class="monospaced">@Model.Author</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p class="discription">@Model.Description</p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalLong">Read now</a>
                </div>
            </div>
            <hr />
            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold">Catagory - </span>@Model.Catagory</li>
                <li class="list-group-item"><span class="font-weight-bold">Total pages - </span>@Model.TotalPages</li>
                <li class="list-group-item"><span class="font-weight-bold">Language - </span>@Model.Language</li>
            </ul>
        </div>
    </div>

   

    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Read Book</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body h-100">
                    <iframe src="@Model.BookPdfURL" class="w-100"></iframe>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>                    
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="py-5 bg-light">
        <h3 class="h3">Simmiler books</h3>
        <div class="row">
            @for (int i = 0; i < 5; i++)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" xmlns="http://www.w3.org/2000/svg"></svg>
                        <div class="card-body">
                            <h5 class="card-title">Title</h5>
                            <p class="card-text">Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="/Books/GetBook" class="btn btn-sm btn-outline-secondary">View Detail</a>
                                </div>
                                <small class="text-muted">Author</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</div>