BookStore/BookStore/Component/TopBooksViewComponent.cs
using BookStore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Component
{
    public class TopBooksViewComponent:ViewComponent
    {
        private readonly BookRepository _bookRepository = null;
        public TopBooksViewComponent(BookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooks(count);
            return View(books);
        }
    }
}

BookStore/BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class HomeController:Controller
    {
        public ViewResult index()
        {
            return View();
        }

        public ViewResult aboutus()
        {
            return View();
        }


        public ViewResult contactus()
        {
            return View();
        }
    }
}

BookStore/BookStore/Views/Home/aboutus.cshtml
@{
    ViewData["Title"] = "aboutus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>aboutus</h1>

BookStore/BookStore/Views/Home/contactus.cshtml
@{
    ViewData["Title"] = "contactus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>contactus</h1>

BookStore/BookStore/Views/Home/index.cshtml
@{
    Layout = "_Layout";
}

<section>
    <div class="jumbotron bg-white text-center">
        <h1 class="display-4 ">Welcome to books  store</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-sm" href="#" role="button">Search Book</a>
    </div>
</section>

<div class="py-5 bg-light">
    <div class="container">
        <h3>Top books</h3>
        @await Component.InvokeAsync("TopBooks",new {count = 3 })
    </div>
</div>